# Generated by Django 3.1.2 on 2020-10-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_imagetest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagetest',
        ),
    ]
